### Get Last Articles
GET http://cardsrealm.com/app/getlastarticles

### Get Media
GET http://cardsrealm.com/app/getmedia

### Get Metagame
GET http://cardsrealm.com/app/get_metagame

### Get Deck by ID
GET http://cardsrealm.com/app/getdeckbyid?deck_id=17731
